#!/usr/bin/env bash

source "$HOME/.config/sketchybar/colors.sh"
#source "$HOME/.config/sketchybar/icons.sh"

CONFIG_DIR="$HOME/.config/sketchybar"
ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="SF Pro"

PADDINGS=3

SHADOW=on

sketchybar --bar     height=34                                         \
                     color=$BAR_COLOR                                  \
                     shadow=$SHADOW                                    \
                     position=bottom                                    \
                     sticky=on                                         \
                     topmost=window                                        \
                     padding_right=12                                  \
                     padding_left=0                                    \
                      corner_radius=9                                   \
                      y_offset=0                                        \
                      margin=10                                         \
                     blur_radius=4                                     \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$PLUGIN_DIR/aerospacer.sh"

sketchybar --update

echo "sketchybar configuation loaded.."
