[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "nvim ~/.dotfiles"

[[session]]
name = "interview_prep"
path = "~/interview_prep"
startup_command = "echo 'gl to me :)'"


[[session]]
name = "home_server"
path = "~/home_server"

[[session]]
name = "BrowserCats"
path = "~"
startup_command = "terminal-browser open cats.com"
